import type {
  Teacher,
  Student,
  Exam,
  Question,
  AnswerOption,
  StudentExamAssignment,
  StudentAnswer,
  Grade,
  ExamLevel,
  QuestionTopic,
  BankQuestion,
  MultipleChoiceConfig,
  NumericConfig,
} from "./types"

// Datos mockeados para desarrollo
export const MOCK_DATA = {
  teacher: {
    id: "1",
    full_name: "Prof. María García",
    email: "maria.garcia@ejemplo.com",
    created_at: new Date().toISOString(),
  } as Teacher,

  students: [
    {
      id: "1",
      teacher_id: "1",
      full_name: "Juan Pérez",
      email: "juan.perez@estudiante.com",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      full_name: "Ana Martínez",
      email: "ana.martinez@estudiante.com",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      teacher_id: "1",
      full_name: "Carlos López",
      email: "carlos.lopez@estudiante.com",
      created_at: new Date().toISOString(),
    },
  ] as Student[],

  levels: [
    {
      id: "1",
      teacher_id: "1",
      name: "Básico",
      description: "Nivel introductorio de ciencias",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      name: "Intermedio",
      description: "Nivel intermedio con conceptos avanzados",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      teacher_id: "1",
      name: "Avanzado",
      description: "Nivel avanzado para estudiantes destacados",
      created_at: new Date().toISOString(),
    },
  ] as ExamLevel[],

  exams: [
    {
      id: "1",
      teacher_id: "1",
      level_id: "1",
      title: "Examen de Física - Cinemática",
      description: "Examen sobre movimiento rectilíneo y caída libre",
      duration_minutes: 60,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      level_id: "2",
      title: "Examen de Química - Estequiometría",
      description: "Cálculos estequiométricos y balanceo de ecuaciones",
      duration_minutes: 90,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Exam[],

  questions: [
    {
      id: "1",
      exam_id: "1",
      question_text:
        "Un objeto se lanza verticalmente hacia arriba con una velocidad inicial de 20 m/s. ¿Cuál es la altura máxima alcanzada?",
      question_latex: "v_0 = 20 \\, \\text{m/s}, \\quad g = 10 \\, \\text{m/s}^2",
      question_image_url: null,
      question_graph_data: null,
      question_order: 1,
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      exam_id: "1",
      question_text: "La ecuación de velocidad de un móvil es:",
      question_latex: "v(t) = 5 + 2t",
      question_image_url: null,
      question_graph_data: null,
      question_order: 2,
      points: 10,
      created_at: new Date().toISOString(),
    },
  ] as Question[],

  answerOptions: [
    {
      id: "1",
      question_id: "1",
      option_text: "10 metros",
      option_latex: "h = 10 \\, \\text{m}",
      option_image_url: null,
      is_correct: false,
      option_order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      question_id: "1",
      option_text: "20 metros",
      option_latex: "h = 20 \\, \\text{m}",
      option_image_url: null,
      is_correct: true,
      option_order: 2,
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      question_id: "1",
      option_text: "30 metros",
      option_latex: "h = 30 \\, \\text{m}",
      option_image_url: null,
      is_correct: false,
      option_order: 3,
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      question_id: "2",
      option_text: "Movimiento uniforme",
      option_latex: null,
      option_image_url: null,
      is_correct: false,
      option_order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      question_id: "2",
      option_text: "Movimiento uniformemente acelerado",
      option_latex: null,
      option_image_url: null,
      is_correct: true,
      option_order: 2,
      created_at: new Date().toISOString(),
    },
  ] as AnswerOption[],

  assignments: [
    {
      id: "1",
      exam_id: "1",
      student_id: "1",
      magic_token: "abc123def456",
      assigned_at: new Date().toISOString(),
      started_at: null,
      submitted_at: null,
      status: "pending" as const,
    },
    {
      id: "2",
      exam_id: "1",
      student_id: "2",
      magic_token: "xyz789uvw012",
      assigned_at: new Date().toISOString(),
      started_at: new Date().toISOString(),
      submitted_at: new Date().toISOString(),
      status: "submitted" as const,
    },
  ] as StudentExamAssignment[],

  studentAnswers: [
    {
      id: "1",
      assignment_id: "2",
      question_id: "1",
      selected_option_id: "2",
      answer_text: null,
      answer_latex: null,
      points_earned: 10,
      feedback: null,
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      assignment_id: "2",
      question_id: "2",
      selected_option_id: "5",
      answer_text: null,
      answer_latex: null,
      points_earned: 10,
      feedback: null,
      created_at: new Date().toISOString(),
    },
  ] as StudentAnswer[],

  grades: [
    {
      id: "1",
      assignment_id: "2",
      total_points: 20,
      points_earned: 20,
      percentage: 100,
      graded_at: new Date().toISOString(),
      graded_by: "1",
    },
  ] as Grade[],

  // ============================================
  // QUESTION BANK DATA
  // ============================================

  topics: [
    {
      id: "1",
      teacher_id: "1",
      name: "Cinemática",
      description: "Movimiento rectilíneo, caída libre, tiro parabólico",
      color: "blue",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      name: "Dinámica",
      description: "Leyes de Newton, fuerzas, fricción",
      color: "green",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      teacher_id: "1",
      name: "Energía",
      description: "Trabajo, energía cinética y potencial, conservación",
      color: "orange",
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      teacher_id: "1",
      name: "Ondas",
      description: "Ondas mecánicas, sonido, luz",
      color: "purple",
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      teacher_id: "1",
      name: "Electromagnetismo",
      description: "Campos eléctricos, magnéticos, circuitos",
      color: "red",
      created_at: new Date().toISOString(),
    },
  ] as QuestionTopic[],

  bankQuestions: [
    {
      id: "bq1",
      teacher_id: "1",
      topic_id: "1",
      title: "Altura máxima en lanzamiento vertical",
      content: `<p>Un objeto se lanza verticalmente hacia arriba con una velocidad inicial de 20 m/s.</p>
<p><strong>¿Cuál es la altura máxima alcanzada?</strong></p>
<p>Considera: $g = 10 \\, \\text{m/s}^2$</p>`,
      question_type: "multiple_choice",
      type_config: {
        options: [
          { id: "opt1", text: "<p>10 metros ($h = 10 \\, \\text{m}$)</p>", is_correct: false, order: 1 },
          { id: "opt2", text: "<p>20 metros ($h = 20 \\, \\text{m}$)</p>", is_correct: true, order: 2 },
          { id: "opt3", text: "<p>30 metros ($h = 30 \\, \\text{m}$)</p>", is_correct: false, order: 3 },
          { id: "opt4", text: "<p>40 metros ($h = 40 \\, \\text{m}$)</p>", is_correct: false, order: 4 },
        ],
        allow_multiple: false,
        shuffle_options: true,
      } as MultipleChoiceConfig,
      difficulty: "easy",
      estimated_time_minutes: 3,
      tags: ["cinemática", "caída libre", "MRU"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 5,
      average_score: 0.75,
    },
    {
      id: "bq2",
      teacher_id: "1",
      topic_id: "1",
      title: "Tipo de movimiento según ecuación",
      content: `<p>La ecuación de velocidad de un móvil es:</p>
<p style="text-align: center;">$v(t) = 5 + 2t$</p>
<p>¿Qué tipo de movimiento describe esta ecuación?</p>`,
      question_type: "multiple_choice",
      type_config: {
        options: [
          { id: "opt1", text: "<p>Movimiento uniforme (MRU)</p>", is_correct: false, order: 1 },
          { id: "opt2", text: "<p>Movimiento uniformemente acelerado (MRUA)</p>", is_correct: true, order: 2 },
          { id: "opt3", text: "<p>Movimiento armónico simple</p>", is_correct: false, order: 3 },
          { id: "opt4", text: "<p>Movimiento circular</p>", is_correct: false, order: 4 },
        ],
        allow_multiple: false,
        shuffle_options: true,
      } as MultipleChoiceConfig,
      difficulty: "easy",
      estimated_time_minutes: 2,
      tags: ["cinemática", "ecuaciones", "MRUA"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 8,
      average_score: 0.85,
    },
    {
      id: "bq3",
      teacher_id: "1",
      topic_id: "1",
      title: "Cálculo de velocidad final",
      content: `<p>Un automóvil acelera uniformemente desde el reposo a razón de $2 \\, \\text{m/s}^2$ durante 10 segundos.</p>
<p><strong>Calcula la velocidad final.</strong></p>
<p><em>Ingresa tu respuesta en m/s</em></p>`,
      question_type: "numeric",
      type_config: {
        correct_value: 20,
        tolerance: 0.5,
        tolerance_type: "absolute",
        unit: "m/s",
        show_unit_input: false,
      } as NumericConfig,
      difficulty: "medium",
      estimated_time_minutes: 4,
      tags: ["cinemática", "MRUA", "aceleración"],
      default_points: 15,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 3,
      average_score: 0.60,
    },
    {
      id: "bq4",
      teacher_id: "1",
      topic_id: "2",
      title: "Segunda Ley de Newton",
      content: `<p>Una fuerza de 50 N actúa sobre un objeto de 10 kg inicialmente en reposo.</p>
<p><strong>¿Cuál es la aceleración del objeto?</strong></p>
<p>Usa la segunda ley de Newton: $F = ma$</p>`,
      question_type: "numeric",
      type_config: {
        correct_value: 5,
        tolerance: 0.1,
        tolerance_type: "absolute",
        unit: "m/s²",
        show_unit_input: false,
      } as NumericConfig,
      difficulty: "easy",
      estimated_time_minutes: 2,
      tags: ["dinámica", "Newton", "fuerza"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 12,
      average_score: 0.90,
    },
    {
      id: "bq5",
      teacher_id: "1",
      topic_id: "3",
      title: "Energía cinética",
      content: `<p>Un objeto de masa 2 kg se mueve a una velocidad de 10 m/s.</p>
<p><strong>Calcula su energía cinética.</strong></p>
<p>Recuerda: $E_k = \\frac{1}{2}mv^2$</p>`,
      question_type: "multiple_choice",
      type_config: {
        options: [
          { id: "opt1", text: "<p>20 J</p>", is_correct: false, order: 1 },
          { id: "opt2", text: "<p>50 J</p>", is_correct: false, order: 2 },
          { id: "opt3", text: "<p>100 J</p>", is_correct: true, order: 3 },
          { id: "opt4", text: "<p>200 J</p>", is_correct: false, order: 4 },
        ],
        allow_multiple: false,
        shuffle_options: true,
      } as MultipleChoiceConfig,
      difficulty: "easy",
      estimated_time_minutes: 3,
      tags: ["energía", "cinética", "trabajo"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 7,
      average_score: 0.80,
    },
    {
      id: "bq6",
      teacher_id: "1",
      topic_id: "4",
      title: "Frecuencia de onda",
      content: `<p>Una onda tiene una longitud de onda de 2 metros y se propaga a 340 m/s.</p>
<p><strong>¿Cuál es su frecuencia?</strong></p>
<p>Usa: $v = \\lambda \\cdot f$</p>`,
      question_type: "numeric",
      type_config: {
        correct_value: 170,
        tolerance: 5,
        tolerance_type: "percentage",
        unit: "Hz",
        show_unit_input: false,
      } as NumericConfig,
      difficulty: "medium",
      estimated_time_minutes: 3,
      tags: ["ondas", "frecuencia", "longitud de onda"],
      default_points: 15,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 4,
      average_score: 0.65,
    },
  ] as BankQuestion[],
}

// Flag para activar/desactivar modo mock
export const USE_MOCK_DATA = process.env.NEXT_PUBLIC_USE_MOCK === "true"
