import type {
  Teacher,
  Student,
  StudentGroup,
  Exam,
  Question,
  AnswerOption,
  ExamAssignment,
  StudentExamAssignment,
  StudentAnswer,
  Grade,
  ExamLevel,
  QuestionTopic,
  BankQuestion,
  MultipleChoiceConfig,
  NumericConfig,
  ExamEvent,
} from "./types"

// Datos mockeados para desarrollo
export const MOCK_DATA = {
  teacher: {
    id: "1",
    full_name: "Prof. María García",
    email: "maria.garcia@ejemplo.com",
    created_at: new Date().toISOString(),
  } as Teacher,

  studentGroups: [
    {
      id: "g1",
      teacher_id: "1",
      name: "TELE2-A",
      year: 2024,
      career: "Ingeniería en Telecomunicaciones",
      created_at: new Date().toISOString(),
    },
    {
      id: "g2",
      teacher_id: "1",
      name: "TELE2-B",
      year: 2024,
      career: "Ingeniería en Telecomunicaciones",
      created_at: new Date().toISOString(),
    },
    {
      id: "g3",
      teacher_id: "1",
      name: "INFO3",
      year: 2024,
      career: "Ingeniería Informática",
      created_at: new Date().toISOString(),
    },
    {
      id: "g4",
      teacher_id: "1",
      name: "ELEC1",
      year: 2024,
      career: "Ingeniería Eléctrica",
      created_at: new Date().toISOString(),
    },
  ] as StudentGroup[],

  students: [
    {
      id: "1",
      teacher_id: "1",
      group_id: "g1",
      full_name: "Juan Pérez",
      email: "juan.perez@estudiante.com",
      year: 2024,
      career: "Ingeniería en Telecomunicaciones",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      group_id: "g1",
      full_name: "Ana Martínez",
      email: "ana.martinez@estudiante.com",
      year: 2024,
      career: "Ingeniería en Telecomunicaciones",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      teacher_id: "1",
      group_id: "g1",
      full_name: "Carlos López",
      email: "carlos.lopez@estudiante.com",
      year: 2024,
      career: "Ingeniería en Telecomunicaciones",
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      teacher_id: "1",
      group_id: "g2",
      full_name: "María González",
      email: "maria.gonzalez@estudiante.com",
      year: 2024,
      career: "Ingeniería en Telecomunicaciones",
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      teacher_id: "1",
      group_id: "g2",
      full_name: "Pedro Ramírez",
      email: "pedro.ramirez@estudiante.com",
      year: 2024,
      career: "Ingeniería en Telecomunicaciones",
      created_at: new Date().toISOString(),
    },
    {
      id: "6",
      teacher_id: "1",
      group_id: "g3",
      full_name: "Laura Fernández",
      email: "laura.fernandez@estudiante.com",
      year: 2024,
      career: "Ingeniería Informática",
      created_at: new Date().toISOString(),
    },
    {
      id: "7",
      teacher_id: "1",
      group_id: "g3",
      full_name: "Diego Morales",
      email: "diego.morales@estudiante.com",
      year: 2024,
      career: "Ingeniería Informática",
      created_at: new Date().toISOString(),
    },
    {
      id: "8",
      teacher_id: "1",
      group_id: null,
      full_name: "Sofia Torres",
      email: "sofia.torres@estudiante.com",
      year: 2023,
      career: "Ingeniería Eléctrica",
      created_at: new Date().toISOString(),
    },
  ] as Student[],

  levels: [
    {
      id: "1",
      teacher_id: "1",
      name: "Básico",
      description: "Nivel introductorio de ciencias",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      name: "Intermedio",
      description: "Nivel intermedio con conceptos avanzados",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      teacher_id: "1",
      name: "Avanzado",
      description: "Nivel avanzado para estudiantes destacados",
      created_at: new Date().toISOString(),
    },
  ] as ExamLevel[],

  exams: [
    {
      id: "1",
      teacher_id: "1",
      level_id: "1",
      title: "Examen de Física - Cinemática",
      description: "Examen sobre movimiento rectilíneo y caída libre",
      duration_minutes: 60,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      level_id: "2",
      title: "Examen de Química - Estequiometría",
      description: "Cálculos estequiométricos y balanceo de ecuaciones",
      duration_minutes: 90,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as Exam[],

  questions: [
    {
      id: "1",
      exam_id: "1",
      question_text:
        "Un objeto se lanza verticalmente hacia arriba con una velocidad inicial de 20 m/s. ¿Cuál es la altura máxima alcanzada?",
      question_latex: "v_0 = 20 \\, \\text{m/s}, \\quad g = 10 \\, \\text{m/s}^2",
      question_image_url: null,
      question_graph_data: null,
      question_order: 1,
      points: 10,
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      exam_id: "1",
      question_text: "La ecuación de velocidad de un móvil es:",
      question_latex: "v(t) = 5 + 2t",
      question_image_url: null,
      question_graph_data: null,
      question_order: 2,
      points: 10,
      created_at: new Date().toISOString(),
    },
  ] as Question[],

  answerOptions: [
    {
      id: "1",
      question_id: "1",
      option_text: "10 metros",
      option_latex: "h = 10 \\, \\text{m}",
      option_image_url: null,
      is_correct: false,
      option_order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      question_id: "1",
      option_text: "20 metros",
      option_latex: "h = 20 \\, \\text{m}",
      option_image_url: null,
      is_correct: true,
      option_order: 2,
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      question_id: "1",
      option_text: "30 metros",
      option_latex: "h = 30 \\, \\text{m}",
      option_image_url: null,
      is_correct: false,
      option_order: 3,
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      question_id: "2",
      option_text: "Movimiento uniforme",
      option_latex: null,
      option_image_url: null,
      is_correct: false,
      option_order: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      question_id: "2",
      option_text: "Movimiento uniformemente acelerado",
      option_latex: null,
      option_image_url: null,
      is_correct: true,
      option_order: 2,
      created_at: new Date().toISOString(),
    },
  ] as AnswerOption[],

  examAssignments: [
    {
      id: "ea1",
      exam_id: "1",
      group_id: "g1",
      title: "Parcial 1 - Cinemática TELE2-A",
      assigned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ea2",
      exam_id: "2",
      group_id: "g3",
      title: "Examen Química INFO3",
      assigned_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ea3",
      exam_id: "1",
      group_id: null,
      title: "Recuperación Cinemática - Sofia Torres",
      assigned_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ] as ExamAssignment[],

  assignments: [
    // Parcial 1 - TELE2-A (3 estudiantes)
    {
      id: "1",
      exam_assignment_id: "ea1",
      exam_id: "1",
      student_id: "1",
      magic_token: "abc123def456",
      assigned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      started_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      submitted_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      status: "graded" as const,
    },
    {
      id: "2",
      exam_assignment_id: "ea1",
      exam_id: "1",
      student_id: "2",
      magic_token: "xyz789uvw012",
      assigned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      started_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      submitted_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      status: "submitted" as const,
    },
    {
      id: "3",
      exam_assignment_id: "ea1",
      exam_id: "1",
      student_id: "3",
      magic_token: "def456ghi789",
      assigned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      started_at: null,
      submitted_at: null,
      status: "pending" as const,
    },
    // Examen Química INFO3 (2 estudiantes)
    {
      id: "4",
      exam_assignment_id: "ea2",
      exam_id: "2",
      student_id: "6",
      magic_token: "jkl012mno345",
      assigned_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      started_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      submitted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      status: "submitted" as const,
    },
    {
      id: "5",
      exam_assignment_id: "ea2",
      exam_id: "2",
      student_id: "7",
      magic_token: "pqr678stu901",
      assigned_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      started_at: null,
      submitted_at: null,
      status: "pending" as const,
    },
    // Recuperación individual
    {
      id: "6",
      exam_assignment_id: "ea3",
      exam_id: "1",
      student_id: "8",
      magic_token: "vwx234yza567",
      assigned_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      started_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      submitted_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      status: "submitted" as const,
    },
  ] as StudentExamAssignment[],

  studentAnswers: [
    {
      id: "1",
      assignment_id: "2",
      question_id: "1",
      selected_option_id: "2",
      answer_text: null,
      answer_latex: null,
      score: 4 as 2 | 3 | 4 | 5,
      feedback: "Buen análisis del movimiento",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      assignment_id: "2",
      question_id: "2",
      selected_option_id: "5",
      answer_text: null,
      answer_latex: null,
      score: 5 as 2 | 3 | 4 | 5,
      feedback: null,
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      assignment_id: "1",
      question_id: "1",
      selected_option_id: "1",
      answer_text: null,
      answer_latex: null,
      score: 3 as 2 | 3 | 4 | 5,
      feedback: "Respuesta parcialmente correcta",
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      assignment_id: "1",
      question_id: "2",
      selected_option_id: "6",
      answer_text: null,
      answer_latex: null,
      score: 4 as 2 | 3 | 4 | 5,
      feedback: null,
      created_at: new Date().toISOString(),
    },
  ] as StudentAnswer[],

  grades: [
    {
      id: "1",
      assignment_id: "1",
      average_score: 3.5,
      final_grade: 4 as const,
      rounding_method: "ceil" as const,
      graded_at: new Date().toISOString(),
      graded_by: "1",
    },
  ] as Grade[],

  // ============================================
  // EXAM MONITORING EVENTS
  // ============================================
  examEvents: [
    // Eventos del estudiante Juan Pérez (assignment "1") - Comportamiento normal
    {
      id: "ev1",
      assignment_id: "1",
      event_type: "exam_started",
      severity: "info",
      timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      details: { message: "El estudiante inició el examen" },
    },
    {
      id: "ev2",
      assignment_id: "1",
      event_type: "tab_hidden",
      severity: "warning",
      timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
      details: { duration_seconds: 8, question_index: 1, message: "Salió de la pestaña brevemente" },
    },
    {
      id: "ev3",
      assignment_id: "1",
      event_type: "tab_visible",
      severity: "info",
      timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000 + 8000).toISOString(),
      details: { message: "Volvió a la pestaña" },
    },
    {
      id: "ev4",
      assignment_id: "1",
      event_type: "exam_submitted",
      severity: "info",
      timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
      details: { message: "Examen enviado correctamente" },
    },

    // Eventos del estudiante Ana Martínez (assignment "2") - Comportamiento sospechoso
    {
      id: "ev5",
      assignment_id: "2",
      event_type: "exam_started",
      severity: "info",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      details: { message: "El estudiante inició el examen" },
    },
    {
      id: "ev6",
      assignment_id: "2",
      event_type: "tab_hidden",
      severity: "critical",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      details: { duration_seconds: 45, question_index: 0, message: "Salió de la pestaña por tiempo prolongado" },
    },
    {
      id: "ev7",
      assignment_id: "2",
      event_type: "tab_visible",
      severity: "info",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000 + 45000).toISOString(),
      details: { message: "Volvió a la pestaña" },
    },
    {
      id: "ev8",
      assignment_id: "2",
      event_type: "paste",
      severity: "critical",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 6 * 60 * 1000).toISOString(),
      details: { pasted_length: 156, question_index: 0, message: "Pegó texto de fuente externa" },
    },
    {
      id: "ev9",
      assignment_id: "2",
      event_type: "window_blur",
      severity: "warning",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
      details: { question_index: 1, message: "La ventana perdió el foco" },
    },
    {
      id: "ev10",
      assignment_id: "2",
      event_type: "window_focus",
      severity: "info",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000 + 3000).toISOString(),
      details: { message: "La ventana recuperó el foco" },
    },
    {
      id: "ev11",
      assignment_id: "2",
      event_type: "right_click",
      severity: "warning",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
      details: { question_index: 1, message: "Intento de abrir menú contextual" },
    },
    {
      id: "ev12",
      assignment_id: "2",
      event_type: "keyboard_shortcut",
      severity: "warning",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
      details: { shortcut_keys: "Ctrl+Shift+I", question_index: 1, message: "Atajo de teclado sospechoso detectado" },
    },
    {
      id: "ev13",
      assignment_id: "2",
      event_type: "devtools_open",
      severity: "critical",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000 + 500).toISOString(),
      details: { message: "Posible apertura de herramientas de desarrollo" },
    },
    {
      id: "ev14",
      assignment_id: "2",
      event_type: "exam_submitted",
      severity: "info",
      timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 50 * 60 * 1000).toISOString(),
      details: { message: "Examen enviado correctamente" },
    },

    // Eventos de Laura Fernández (assignment "4") - Con problemas de conexión
    {
      id: "ev15",
      assignment_id: "4",
      event_type: "exam_started",
      severity: "info",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      details: { message: "El estudiante inició el examen" },
    },
    {
      id: "ev16",
      assignment_id: "4",
      event_type: "connection_lost",
      severity: "warning",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
      details: { question_index: 0, message: "Se perdió la conexión a internet" },
    },
    {
      id: "ev17",
      assignment_id: "4",
      event_type: "connection_restored",
      severity: "info",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
      details: { message: "Conexión restaurada" },
    },
    {
      id: "ev18",
      assignment_id: "4",
      event_type: "idle_timeout",
      severity: "warning",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 35 * 60 * 1000).toISOString(),
      details: { idle_duration_seconds: 180, question_index: 1, message: "Inactividad prolongada detectada" },
    },
    {
      id: "ev19",
      assignment_id: "4",
      event_type: "browser_resize",
      severity: "info",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000).toISOString(),
      details: { window_dimensions: { width: 1024, height: 768 }, message: "Cambio de tamaño de ventana" },
    },
    {
      id: "ev20",
      assignment_id: "4",
      event_type: "exam_submitted",
      severity: "info",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
      details: { message: "Examen enviado correctamente" },
    },

    // Eventos de Sofia Torres (assignment "6") - Intento de copia
    {
      id: "ev21",
      assignment_id: "6",
      event_type: "exam_started",
      severity: "info",
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      details: { message: "El estudiante inició el examen" },
    },
    {
      id: "ev22",
      assignment_id: "6",
      event_type: "copy",
      severity: "warning",
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      details: { question_index: 0, message: "El estudiante copió texto del examen" },
    },
    {
      id: "ev23",
      assignment_id: "6",
      event_type: "print_attempt",
      severity: "critical",
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
      details: { question_index: 0, message: "Intento de imprimir detectado" },
    },
    {
      id: "ev24",
      assignment_id: "6",
      event_type: "fullscreen_exit",
      severity: "warning",
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
      details: { question_index: 1, message: "Salió del modo pantalla completa" },
    },
    {
      id: "ev25",
      assignment_id: "6",
      event_type: "rapid_answers",
      severity: "warning",
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
      details: { answer_time_seconds: 3, question_index: 1, message: "Respuesta muy rápida (posible adivinanza)" },
    },
    {
      id: "ev26",
      assignment_id: "6",
      event_type: "exam_submitted",
      severity: "info",
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
      details: { message: "Examen enviado correctamente" },
    },
  ] as ExamEvent[],

  // ============================================
  // QUESTION BANK DATA
  // ============================================

  topics: [
    {
      id: "1",
      teacher_id: "1",
      name: "Cinemática",
      description: "Movimiento rectilíneo, caída libre, tiro parabólico",
      color: "blue",
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      teacher_id: "1",
      name: "Dinámica",
      description: "Leyes de Newton, fuerzas, fricción",
      color: "green",
      created_at: new Date().toISOString(),
    },
    {
      id: "3",
      teacher_id: "1",
      name: "Energía",
      description: "Trabajo, energía cinética y potencial, conservación",
      color: "orange",
      created_at: new Date().toISOString(),
    },
    {
      id: "4",
      teacher_id: "1",
      name: "Ondas",
      description: "Ondas mecánicas, sonido, luz",
      color: "purple",
      created_at: new Date().toISOString(),
    },
    {
      id: "5",
      teacher_id: "1",
      name: "Electromagnetismo",
      description: "Campos eléctricos, magnéticos, circuitos",
      color: "red",
      created_at: new Date().toISOString(),
    },
  ] as QuestionTopic[],

  bankQuestions: [
    {
      id: "bq1",
      teacher_id: "1",
      topic_id: "1",
      title: "Altura máxima en lanzamiento vertical",
      content: `<p>Un objeto se lanza verticalmente hacia arriba con una velocidad inicial de 20 m/s.</p>
<p><strong>¿Cuál es la altura máxima alcanzada?</strong></p>
<p>Considera: $g = 10 \\, \\text{m/s}^2$</p>`,
      question_type: "multiple_choice",
      type_config: {
        options: [
          { id: "opt1", text: "<p>10 metros ($h = 10 \\, \\text{m}$)</p>", is_correct: false, order: 1 },
          { id: "opt2", text: "<p>20 metros ($h = 20 \\, \\text{m}$)</p>", is_correct: true, order: 2 },
          { id: "opt3", text: "<p>30 metros ($h = 30 \\, \\text{m}$)</p>", is_correct: false, order: 3 },
          { id: "opt4", text: "<p>40 metros ($h = 40 \\, \\text{m}$)</p>", is_correct: false, order: 4 },
        ],
        allow_multiple: false,
        shuffle_options: true,
      } as MultipleChoiceConfig,
      difficulty: "easy",
      estimated_time_minutes: 3,
      tags: ["cinemática", "caída libre", "MRU"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 5,
      average_score: 0.75,
    },
    {
      id: "bq2",
      teacher_id: "1",
      topic_id: "1",
      title: "Tipo de movimiento según ecuación",
      content: `<p>La ecuación de velocidad de un móvil es:</p>
<p style="text-align: center;">$v(t) = 5 + 2t$</p>
<p>¿Qué tipo de movimiento describe esta ecuación?</p>`,
      question_type: "multiple_choice",
      type_config: {
        options: [
          { id: "opt1", text: "<p>Movimiento uniforme (MRU)</p>", is_correct: false, order: 1 },
          { id: "opt2", text: "<p>Movimiento uniformemente acelerado (MRUA)</p>", is_correct: true, order: 2 },
          { id: "opt3", text: "<p>Movimiento armónico simple</p>", is_correct: false, order: 3 },
          { id: "opt4", text: "<p>Movimiento circular</p>", is_correct: false, order: 4 },
        ],
        allow_multiple: false,
        shuffle_options: true,
      } as MultipleChoiceConfig,
      difficulty: "easy",
      estimated_time_minutes: 2,
      tags: ["cinemática", "ecuaciones", "MRUA"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 8,
      average_score: 0.85,
    },
    {
      id: "bq3",
      teacher_id: "1",
      topic_id: "1",
      title: "Cálculo de velocidad final",
      content: `<p>Un automóvil acelera uniformemente desde el reposo a razón de $2 \\, \\text{m/s}^2$ durante 10 segundos.</p>
<p><strong>Calcula la velocidad final.</strong></p>
<p><em>Ingresa tu respuesta en m/s</em></p>`,
      question_type: "numeric",
      type_config: {
        correct_value: 20,
        tolerance: 0.5,
        tolerance_type: "absolute",
        unit: "m/s",
        show_unit_input: false,
      } as NumericConfig,
      difficulty: "medium",
      estimated_time_minutes: 4,
      tags: ["cinemática", "MRUA", "aceleración"],
      default_points: 15,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 3,
      average_score: 0.60,
    },
    {
      id: "bq4",
      teacher_id: "1",
      topic_id: "2",
      title: "Segunda Ley de Newton",
      content: `<p>Una fuerza de 50 N actúa sobre un objeto de 10 kg inicialmente en reposo.</p>
<p><strong>¿Cuál es la aceleración del objeto?</strong></p>
<p>Usa la segunda ley de Newton: $F = ma$</p>`,
      question_type: "numeric",
      type_config: {
        correct_value: 5,
        tolerance: 0.1,
        tolerance_type: "absolute",
        unit: "m/s²",
        show_unit_input: false,
      } as NumericConfig,
      difficulty: "easy",
      estimated_time_minutes: 2,
      tags: ["dinámica", "Newton", "fuerza"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 12,
      average_score: 0.90,
    },
    {
      id: "bq5",
      teacher_id: "1",
      topic_id: "3",
      title: "Energía cinética",
      content: `<p>Un objeto de masa 2 kg se mueve a una velocidad de 10 m/s.</p>
<p><strong>Calcula su energía cinética.</strong></p>
<p>Recuerda: $E_k = \\frac{1}{2}mv^2$</p>`,
      question_type: "multiple_choice",
      type_config: {
        options: [
          { id: "opt1", text: "<p>20 J</p>", is_correct: false, order: 1 },
          { id: "opt2", text: "<p>50 J</p>", is_correct: false, order: 2 },
          { id: "opt3", text: "<p>100 J</p>", is_correct: true, order: 3 },
          { id: "opt4", text: "<p>200 J</p>", is_correct: false, order: 4 },
        ],
        allow_multiple: false,
        shuffle_options: true,
      } as MultipleChoiceConfig,
      difficulty: "easy",
      estimated_time_minutes: 3,
      tags: ["energía", "cinética", "trabajo"],
      default_points: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 7,
      average_score: 0.80,
    },
    {
      id: "bq6",
      teacher_id: "1",
      topic_id: "4",
      title: "Frecuencia de onda",
      content: `<p>Una onda tiene una longitud de onda de 2 metros y se propaga a 340 m/s.</p>
<p><strong>¿Cuál es su frecuencia?</strong></p>
<p>Usa: $v = \\lambda \\cdot f$</p>`,
      question_type: "numeric",
      type_config: {
        correct_value: 170,
        tolerance: 5,
        tolerance_type: "percentage",
        unit: "Hz",
        show_unit_input: false,
      } as NumericConfig,
      difficulty: "medium",
      estimated_time_minutes: 3,
      tags: ["ondas", "frecuencia", "longitud de onda"],
      default_points: 15,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      times_used: 4,
      average_score: 0.65,
    },
  ] as BankQuestion[],
}

// Flag para activar/desactivar modo mock
export const USE_MOCK_DATA = process.env.NEXT_PUBLIC_USE_MOCK === "true"
